name: OBAKitTests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# GitHub macOS Runner images are documented at:
# https://github.com/actions/runner-images?tab=readme-ov-file
# Installed versions of Xcode on macOS 26 are documented at:
# https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md

jobs:
  build:
    runs-on: macos-26-arm64

    steps:
    - uses: actions/checkout@v6

    - uses: actions/cache@v5
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Switch Xcode
      run: sudo xcode-select -switch /Applications/Xcode_26.2.app

    - name: Install xcodegen
      run: brew install xcodegen

    - name: Generate xcodeproj for OneBusAway
      run: scripts/generate_project OneBusAway

    # Build
    - name: Build OneBusAway
      run: xcodebuild clean build-for-testing
        -scheme 'App'
        -destination 'platform=iOS Simulator,name=iPhone 16'
        -quiet

    # Unit Test
    - name: OBAKit Unit Test
      run: xcodebuild test-without-building
        -only-testing:OBAKitTests
        -project 'OBAKit.xcodeproj'
        -scheme 'App'
        -destination 'platform=iOS Simulator,name=iPhone 16'
        -resultBundlePath OBAKitTests.xcresult
        -quiet

    # Upload results
    - uses: kishikawakatsumi/xcresulttool@v1.7.0
      continue-on-error: true
      with:
        show-passed-tests: false    # Avoid truncation of annotations by GitHub by omitting succeeding tests.
        path: |
          OBAKitTests.xcresult
      if: success() || failure()
